"""empty message

Revision ID: 0033 drop tickets.old_event_id
Revises: 0032 orders,tickets,ticket_types
Create Date: 2019-09-25 01:01:37.092066

"""

# revision identifiers, used by Alembic.
revision = '0033 drop tickets.old_event_id'
down_revision = '0032 orders,tickets,ticket_types'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'old_event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('old_event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
